
  Performance statistics for DSP solver: icalls =      1

 ===========================
 = multifrontal statistics =
 ===========================

     number of equations                     =            6240
     no. of nonzeroes in lower triangle of a =          386664
     no. of nonzeroes in the factor l        =         1398681
     ratio of nonzeroes in factor (min/max)  =          0.9653
     number of super nodes                   =             137
     maximum order of a front matrix         =             375
     maximum size of a front matrix          =           70500
     maximum size of a front trapezoid       =           64284
     no. of floating point ops for factor    =      3.1589D+08
     no. of floating point ops for solve     =      5.2459D+06
     ratio of flops for factor (min/max)     =          0.9760
     negative pivot monitoring activated
     number of negative pivots encountered   =               0
     factorization panel size                =             128
     number of cores used                    =               2
     time (cpu & wall) for structure input   =        0.000000        0.002302
     time (cpu & wall) for ordering          =        0.062500        0.029137
     time (cpu & wall) for other matrix prep =        0.000000        0.002364
     time (cpu & wall) for value input       =        0.031250        0.005683
     time (cpu & wall) for matrix distrib.   =        0.031250        0.021557
     time (cpu & wall) for numeric factor    =        0.093750        0.041606
     computational rate (gflops) for factor  =        3.369529        7.592477

     i/o stats: unit-Core          file length             amount transferred
                                 words       mbytes          words       mbytes
                   ----     ----------     --------     ----------     --------
                95-   0         32768.        0. MB         21403.        0. MB
                95-   1         32768.        0. MB         20604.        0. MB

                -------     ----------     --------     ----------     --------
                Totals:         65536.        0. MB         42007.        0. MB


  Solver Memory allocated on core    0       =       14.134 MB
  Solver Memory allocated on core    1       =       13.580 MB
  Total Solver Memory allocated by all cores =       27.714 MB

